name: PHPT Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpt-test:
    name: "PHPT Tests"
    strategy:
      fail-fast: false
      matrix:
#        os: [macos-latest, ubuntu-latest]
        os: [ubuntu-latest]
        php-versions: [8.0, 8.1, 8.2]
#        zts-mode: [zts, nts]
        zts-mode: [zts]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
      - name: "Build SDL2_mixer extension"
        run: |
          sudo apt-get update -qq
          sudo usermod -a -G audio github
          sudo apt-get install -y portaudio19-dev
          sudo apt-get install -y libasound2-dev alsa-utils alsa-oss
          sudo apt-get install -y lame
          sudo apt-get install linux-modules-extra-$(uname -r)
          sudo bash tests/prep-snd-dummy.sh
          sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install libsdl2-mixer-dev
          sudo pecl update-channels
          sudo pecl install sdl-beta
          phpize
          ./configure --with-sdl_mixer
          make
      - name: "Run the tests"
        uses: coactions/setup-xvfb@v1
        with:
          run: |
            php run-tests.php -d extension=sdl.so -d extension=`pwd`/modules/sdl_mixer.so  --offline --show-diff --set-timeout 120 -q
          working-directory: ./
          options: -screen 0 1200x1024x24
