name: PHPT Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpt-test:
    name: "PHPT Tests"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, fedora]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build SDL_mixer extension ${{ matrix.os }}
        run: docker build -t sdl_mixer:${{ matrix.os }} -f Dockerfile.${{ matrix.os }} .
      - name: Run tests on ${{ matrix.os }}
        run: docker run --rm sdl_mixer:${{ matrix.os }}
